### ISSUE TITLE
Add a quit event/handler

### ISSUE THREAD

**Issue by fluffynukeit** [HeinrichApfelmus/threepenny-gui#37]
TPG should offer users a way to register actions to be triggered when a user disconnects, navigates away from the page, closes the window, etc.  Among other things, this would allow easy freeing of resources that were allocated for the user's session.

**Comment by Porges** [comment]
A random but associated question: how can I cleanly make the server quit? I resorted to attempting to `exitWith` but that only results in a console message and the server continues to run (I assume the server is catching and handling exceptions on the threads).

**Comment by HeinrichApfelmus** [comment]
@Porges Please feel free to open a new issue, to keep topics separate.

To answer your question, Threepenny runs everything in separate threads, and the documentation for `exitWith` indicates that exiting a thread may not quite the whole program — which makes sense, since there might be other browser windows connected to the server. See also the blog post ["Exiting a Haskell process"][1].

  [1]: https://www.fpcomplete.com/blog/2017/08/exiting-haskell-process
